config/routes.rb
Leasingx::Engine.routes.draw do

  mount Authentify::Engine => "/authentify"  #, :as => "authentify_engine"
  mount Customerx::Engine => "/customerx"  #, :as => "authentify_engine"

  match '/view_handler', :to => 'application#view_handler'

  resources :customer
  resources :lease_logs
  resources :lease_bookings
  resources :lease_bookings do
    collection do
      get 'search'
      put 'search_results'
      get 'stats'
      put 'stats_results'
    end
    resources :lease_logs
    match '/lease_bookings/setst', :to => 'lease_bookings#setst'
  end

  resources :lease_items do
    collection do
      get 'search'
      put 'search_results'
    end
  end

end

app/controllers/leasingx/application_controller.rb
module Leasingx
  class ApplicationController < ActionController::Base
    include Authentify::SessionsHelper
    include Authentify::UserPrivilegeHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
  end
end

app/controllers/leasingx/lease_bookings_controller.rb
# encoding: utf-8

module Leasingx
  class LeaseBookingsController < ApplicationController
    before_filter :require_signin
    before_filter :require_employee  
    
    helper_method :has_create_right?, :has_show_right?, :has_update_right?, :has_stats_right?, :set_time_slot, :no_change_on_discount?, :return_purpose
    
    def index
      @title = '设备出租Booking'
      @lease_bookings = LeaseBooking.where("lease_date >= ?", Time.now - 365.day).order("lease_date DESC, customer_id, start_time").paginate(:per_page => 40, :page => params[:page])
      respond_to do |format|
        format.html
        format.js
        format.json { render json: @lease_bookings }
      end
    end
  
    def new
      @title = "输入Booking"
      if has_create_right?
        @lease_booking = LeaseBooking.new(params[:lease_booking], :as => :roles_new)
        @start_time = params[:start_time]
        @start_time_options = Array.new
        @end_time_options = Array.new
        @lease_item = LeaseItem.find_by_id(params[:lease_booking][:lease_item_id].to_i) if params[:lease_booking].present?
        
        respond_to do |format|
          format.html
          format.js
          format.json { render json: @lease_booking}
        end
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=无权限输入出租Booking！")
      end
   
    end
  
    def create
      if has_create_right?
        @lease_booking = LeaseBooking.new(params[:lease_booking], :as => :roles_new)
        @lease_booking.sales_id = Customerx::Customer.find_by_id(params[:lease_booking][:customer_id].to_i).sales_id  #session[:user_id]
        @lease_booking.input_by_id = session[:user_id]
        @lease_booking.item_hourly_rate = LeaseItem.find_by_id(params[:lease_booking][:lease_item_id].to_i).hourly_rate
        
        if @lease_booking.save
            #send out email if saved
      
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=Booking已保存！")
        else
          flash.now[:error] = "Booking无法保存！"
          render 'new'
        end
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=无权限输入出租Booking！")
      end    
    end
  
    def edit
      @title = "更改Booking"
      @lease_booking = LeaseBooking.find(params[:id])
      @new_lease_booking = LeaseBooking.new(params[:lease_booking], :as => :roles_new)
      @start_time = params[:start_time]
      @start_time_options = Array.new
      @end_time_options = Array.new
      @start_time_options << @lease_booking.start_time
      @end_time_options << @lease_booking.end_time
       
      if !has_update_right?
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=无更改Booking权限！")
      else
        respond_to do |format|
          format.html
          format.js
          format.json { render json: @lease_booking}
        end
      end
      
    end
  
    def update
      @lease_booking = LeaseBooking.find(params[:id])    
      if has_update_right?
        @lease_booking.input_by_id = session[:user_id]
        if @lease_booking.update_attributes(params[:lease_booking], :as => :roles_update)
          #update charge_rate
          if @lease_booking.lease_item_id_changed? || @lease_booking.discount_changed?
            @lease_booking.update_attribute(:charge_rate, LeaseItem.find_by_id(@lease_booking.lease_item_id).hourly_rate *
                                     (100 - @lease_booking.discount)/100.00)
          end
            #send out email with change listed
          #if @lease_booking.changed         
          #end
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=Booking更改已保存!")
        else
          flash.now[:error] = "无法保存Booking更改"
          render 'edit'
   
        end
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=无更改Booking权限！")
      end    
    end
  
    def destroy
      if has_destroy_right?
        @lease_booking = LeaseBooking.find(params[:id])
        @lease_booking.destroy
      
        redirect_to URI.escape(SUBURI + "/view_handler?index=0msg=Booking已删除")
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0msg=无删除权限")
      end
    end
  
    def show
      @title = "Booking内容"
      @lease_booking = LeaseBooking.find(params[:id])
      if !has_show_right?(@lease_booking)
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=无权限查看出租Booking")
      end
    end
    
    def search
      @lease_booking = LeaseBooking.new
    end
    
    def search_results
      @lease_booking = LeaseBooking.new(params[:lease_booking], :as => :roles_search)   
      @lease_bookings = @lease_booking.find_lease_bookings #.paginate(:per_page => 40, :page => params[:page])
      #seach params
      @search_params = search_params()    
    end
    
    def stats
      if has_stats_right?
        @lease_booking = LeaseBooking.new
      end
    end
    
    def stats_results
      if has_stats_right?
        @lease_booking = LeaseBooking.new(params[:lease_booking], :as => :roles_search)
      
        @lease_bookings = @lease_booking.find_lease_bookings
        
        @lease_bookings_stats = @lease_bookings.where("cancelled = ? AND completed = ?", false, true).order('lease_date DESC')
        @stats_params = "参数："+params[:lease_booking][:time_frame] + '，统计条数：'+ @lease_bookings.count.to_s
        group_bookings(params[:lease_booking][:time_frame]) #result in @lease_bookings_stats & @stats_params
        #retrieve stats parameters     
        @stats_params += ', ' + Customer.find_by_id(params[:lease_booking][:customer_id_search]).short_name if params[:lease_booking][:customer_id_search].present?
        @stats_params += ', ' + LeaseItem.find_by_id(params[:lease_booking][:lease_item_id_search]).name if params[:lease_booking][:lease_item_id_search].present?
        @stats_params += ', ' + User.find_by_id(params[:lease_booking][:sales_id_search]).name if params[:lease_booking][:sales_id_search].present?
  
        return if @lease_bookings_stats.blank?  #empty @lease_bookings_stats causes error in following code      
      else
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=无统计权限！")
      end     
    end
    
    protected
    
    def group_bookings(time_frame)
        #charge_rate in booking is the rate after discount.
        case time_frame #params[:lease_booking][:time_frame]
        when '周'
          @lease_bookings_stats = @lease_bookings_stats.where("lease_date > ?", 2.years.ago).all(:select => "lease_date, sum(total_hour) as total_hours, sum(total_hour * charge_rate ) as revenue, count(DISTINCT(customer_id)) as num_customer", 
                                  :group => "strftime('%Y/%W', lease_date)")
                            
        when '月'
          @lease_bookings_stats = @lease_bookings_stats.where("lease_date > ?", 3.years.ago).all(:select => "lease_date, sum(total_hour) as total_hours, sum(total_hour * charge_rate ) as revenue, count(DISTINCT(customer_id)) as num_customer", 
                                  :group => "strftime('%Y/%m', lease_date)")                     
        when '季'
          @lease_bookings_stats = @lease_bookings_stats.where("lease_date > ?", 4.years.ago).all(:select => "lease_date, sum(total_hour) as total_hours, sum(total_hour * charge_rate ) as revenue, count(DISTINCT(customer_id)) as num_customer,
                                  CASE WHEN cast(strftime('%m', lease_date) as integer) BETWEEN 1 AND 3 THEN 1 WHEN cast(strftime('%m', lease_date) as integer) BETWEEN 4 and 6 THEN 2 WHEN cast(strftime('%m', lease_date) as integer) BETWEEN 7 and 9 THEN 3 ELSE 4 END as quarter", 
                                  :group => "strftime('%Y', lease_date), quarter")                                
        when '年'
          @lease_bookings_stats = @lease_bookings_stats.where("lease_date > ?", 5.years.ago).all(:select => "lease_date, sum(total_hour) as total_hours, sum(total_hour * charge_rate ) as revenue, count(DISTINCT(customer_id)) as num_customer",
                                  :group => "strftime('%Y', lease_date)")                         
        end   
        
    end
    
    def search_params
      search_params = "参数："
      search_params += ' 开始日期：' + params[:lease_booking][:earliest_lease_date_search] if params[:lease_booking][:earliest_lease_date_search].present?
      search_params += ', 结束日期：' + params[:lease_booking][:latest_lease_date_search] if params[:lease_booking][:latest_lease_date_search].present?
      search_params += ', 测试项目 ：' + LeaseItem.find_by_id(params[:lease_booking][:lease_item_id_search]).name if params[:lease_booking][:lease_item_id_search].present?
      search_params += ', 客户 ：' + Customer.find_by_id(params[:lease_booking][:customer_id_search].to_i).short_name if params[:lease_booking][:customer_id_search].present?
      search_params += ', 业务员 ：' + User.find_by_id(params[:lease_booking][:sales_id_search].to_i).name if params[:lease_booking][:sales_id_search].present?
      search_params
    end  
    
    
    def has_create_right?
      grant_access?('create', 'leasingx_lease_bookings', nil, nil)
    end
    
    def has_update_right?
      grant_access?('update', 'leasingx_lease_bookings', nil, nil)
    end
    
    
    def has_stats_right?
      grant_access?('stats_results', 'leasingx_lease_bookings', nil, nil)
    end
    
    
    def has_show_right?(booking)
      grant_access?('show', 'leasingx_lease_bookings', nil, nil)
    end 
    
    def has_destroy_right?
      grant_access?('destroy', 'leasingx_lease_bookings', nil, nil)
    end
    
    def no_change_on_discount?(discount)
      true if sales? && discount > 10  
      true if sales_dept_head? && discount > 50
      false # for ceo and corp head
    end
    
    def set_time_slot

app/helpers/leasingx/application_helper.rb
# encoding: UTF-8
module Leasingx

    module ApplicationHelper
      def title
        base_title = "EMC Lab"
        if @title.nil?
          base_title
        else
          "#{base_title} | #{@title}"
        end
      end
    
      def return_sales
        return User.user_status('active').user_type('employee').joins(:user_levels).where(:user_levels => {:role => ['sales','sales_dept_head', 'corp_head']}).order("name ASC")    
      end
        
      def link_to_remove_nest_fields(name, f)  
        f.hidden_field(:_destroy) + link_to_function(name, "remove_nest_fields(this)")  
      end  
      
      def link_to_add_nest_fields(name, f, association)  
          new_object = f.object.class.reflect_on_association(association).klass.new  
          fields = f.simple_fields_for(association, new_object, :child_index => "new_#{association}") do |builder|  
            render(association.to_s.singularize + "_fields", :f => builder)  
          end  
          link_to_function(name, ("add_nest_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"))  
      end  
      
      def return_expense_type
        return ['生产开支', '非生产开支']
      end 
      
      def return_expense_for_production
        return ['设备采购','设备校准','设备维护/修', '外包费用', '耗材','零部件','佣金','快递费','接待费','杂项'] 
      end 
      
      def return_expense_for_overhead
        return ['水电','房租','办公用品','卫生用品','油-汽车','维修-汽车','保险-汽车','路桥-汽车','其他-汽车','工资','加班','福利','奖金','网络-通讯','固话-通讯','移动-通讯','业务提成','差旅费','餐费','交际','交通费','广告费','国税','地税','杂项']
      end
      
      def to_chn(str_sym)
        h = {:username => '用户名', 
          :password => '密码', 
          :password_confirmation => '确认密码',
          :user_type => '用户类型',
          :user_levels => '用户职位',
          :role => '职位',
          :updated_at => '修改时间',
          'eng' => '测试工程',
          'customer' => '客户',
          'subcontractor' => '外包商',
          'employee' => '公司员工',
          :sales => '业务员',
          :eng => '工程师',
          :search => '搜索',
          :standard => '测试标准',
          :test_item => '测试项目',
          :lease_usage_record => '测试记录单',
          :quote => '报价单',
          :invoice => '账单',
          :invoice_date => '付款日期',
          :paid_out_date => '付清日期',
          :overdue_days => '过期未付天数',
          :test_plan => '开案单',
          :customer => '客户',
          :earliest_created_at => '最早创建日期',
          :latest_created_at => '最晚创建日期',
          :category => '产品/厂家分类',
          :search_results => '搜索结果',
          :stats => '统计',
          :keyword => '关键字'}
        h[str_sym]
      end
      
      def corp_title
        corp_title = "深圳市劲升硕科技有限公司"
      end
      
      def set_time_slot
        @time_slot = ['12:00 AM','00:30 AM','01:00 AM','01:30 AM','02:00 AM','02:30 AM','03:00 AM' ,'03:30 AM','04:00 AM','04:30 AM','05:00 AM','05:30 AM','06:00 AM','06:30 AM','07:00 AM','07:30 AM','08:00 AM','08:30 AM',
                      '09:00 AM','09:30 AM','10:00 AM','10:30 AM','11:00 AM','11:30 AM','12:00 PM','12:30 PM','01:00 PM','01:30 PM','02:00 PM','02:30 PM','03:00 PM' ,'03:30 PM','04:00 PM','04:30 PM','05:00 PM',
                      '05:30 PM','06:00 PM','06:30 PM','07:00 PM','07:30 PM','08:00 PM','08:30 PM','09:00 PM','09:30 PM','10:00 PM','10:30 PM','11:00 PM','11:30 PM']   
      end
      
      def return_time_frame
        ['周','月','季','年']  #week, month, quarter, year
      end
      
      def return_time_frame1
        ['月','年']  # month, year
      end  
    end
    
end

app/helpers/leasingx/lease_bookings_helper.rb
module Leasingx
  
    module LeaseBookingsHelper
      
          
      
      def booked_time_slots (lease_booking, o_lease_booking)
        slots = Hash.new
        if lease_booking
          lease_booked_list = LeaseBooking.where("Date(lease_date) = :lease_date and lease_item_id = :lease_item_id", 
                                                  :lease_date => lease_booking.lease_date, :lease_item_id => lease_booking.lease_item_id)
          if lease_booked_list.empty?
            slots[Time.strptime("24:00", "%H:%M")] = Time.strptime("24:00", "%H:%M")
          else
            lease_booked_list.each do |lbl|
              unless o_lease_booking && (lbl.start_time == o_lease_booking.start_time)
                slots[Time.strptime(lbl.start_time, '%I:%M %p')]=Time.strptime(lbl.end_time, '%I:%M %p')
              end
            end
          end
        end
        slots
      end 
      
      def start_time_slots (lease_booking, o_lease_booking)
        s_slots = Array.new
        empty_slots = empty_time_slots(lease_booking, o_lease_booking)
        empty_slots.keys.each do |es|
          s_slots << es
          for i in 0...empty_slots[es].length - 1
            s_slots << empty_slots[es][i]
          end
        end
        s_slots
      end
      
      def end_time_slots (lease_booking, o_lease_booking, start_time)
        e_slots = Array.new
        empty_slots = empty_time_slots(lease_booking, o_lease_booking)
        
        if empty_slots.has_key?(start_time)
          e_slots = empty_slots[start_time]
        else
          b = false
          a_empty_slots = empty_slots[find_start_time(empty_slots, start_time)]
          a_empty_slots.each do |aes|
            if b
              e_slots << aes
            end
            if aes == start_time
              b = true
            end     
          end
        end
          
        e_slots
      end
      
      def empty_time_slots(lease_booking, o_lease_booking)
        booked_slots = booked_time_slots(lease_booking, o_lease_booking)
        empty_slots = Hash.new
        
        #if !booked_slots.empty?
          d_start = Time.strptime("00:00", "%H:%M")
          d_end = Time.strptime("24:00", "%H:%M")
          start_time = booked_slots.keys.sort << d_end
          
          if start_time[0] != d_start
            empty_slots[d_start.strftime("%I:%M %p")]=e_time_slots(d_start, start_time[0])
            d_start=booked_slots[start_time[0]]
          end
          start_time.each do |x|
            if d_start == x
              d_start = booked_slots[x]
            else
              empty_slots[d_start.strftime("%I:%M %p")] = e_time_slots(d_start, x)
              d_start = booked_slots[x]
            end
          #end
        end
        empty_slots 
      end
      
      def e_time_slots (start_time, end_time)
        slots = Array.new
        until start_time >= end_time
          start_time += 1800
          slots << start_time.strftime("%I:%M %p")
        end
        slots
      end
      
      def find_start_time(empty_slots, start_time)
        s_time = nil
      
        empty_slots.keys.each do |es|
          for i in 0...empty_slots[es].length
            if empty_slots[es][i] == start_time         
              return es
            end
          end
        end
      end
    end

end

app/views/leasingx/lease_bookings/_form_new.html.erb
<%= simple_form_for @lease_booking do |f| %>    
  <%= hidden_field_tag :start_time, params[:start_time] %>
  <%= hidden_field_tag :form_type, 'new' %>
  
  <%= f.input :lease_date, :label => "租赁日期 ：", :as => :string %>
  <%= f.input :customer_id, :collection => Customerx::Customer.active_cust.all(:order => 'name'), :label_method => :name, :value_method => :id, :prompt => "选客户", :label => "客户 ："  %>
  <%= f.input :lease_item_id, :collection => Leasingx::LeaseItem.active_lease_item.all(:order => 'name'), :label_method => :name, :value_method => :id, :prompt => "选设备", :label => "设备 ："  %>
  <%= f.input :start_time, :label => "开始时间：", :collection => @start_time_options, :prompt => "选开始时间" %>
  <%= f.input :end_time, :label => "结束时间：" , :collection => @end_time_options, :prompt => "选结束时间" %>
  <div style="padding-left:6px" id="lease_booking_hourly_rate">标准价格￥/小时：&nbsp;&nbsp; <%= @lease_booking.charge_rate %></div> <p></p>
  <%= f.input :total_hour, :label => "小时数 ：" %> 
  <%= f.input :charge_rate, :label => "实际价格￥/时 ：" %> 
  <%= f.input :discount, :label => "折扣% ：", :readonly => true %> 
  <%= f.input :leasee_name, :label => "承租人 ：" %> 
  <%= f.input :leasee_phone, :label => "承租人电话：" %>     
  <%= f.input :lease_purpose, :collection => return_purpose, :as => :radio_buttons, :label => "租赁目的: "  %>    
  <%= f.input :note, :as => :text, :input_html => {:rows => '2', :cols => '60' }, :label => "注释 ：" %>   
  <%= f.button :submit, '保存' %>  
<% end %> 

app/views/leasingx/lease_bookings/destroy.html.erb
<h1>LeaseBookings#destroy</h1>
<p>Find me in app/views/lease_bookings/destroy.html.erb</p>

app/views/leasingx/lease_bookings/edit.html.erb
<div id="main_body">

<h1>更改Booking</h1>

<%= render 'form_edit' %>

<%= link_to 'Back', SUBURI + "/view_handler?index=0" %>
</div>

app/views/leasingx/lease_bookings/index.html.erb
<div id="main_body">
	<h1>设备出租Booking</h1>
<div class="emclab_pagination"><%= will_paginate %></div>
</p>
<table>
  <tr>
  	<th>#</th>
    <th>租赁日期</th>
    <th>设备名称</th>    
    <th>开始时间</th>
    <th>小时数</th>
    <th>客户</th>
    <th>业务员</th>
    <th>完成？</th>
    <th>取消？</th>    
    <th></th>
    <th></th>
  </tr>
  <% @lease_bookings.each do |booking| %>
    <tr>
      <% if has_show_right?(booking) %>
        <td><%= link_to booking.id.to_s, SUBURI + "/view_handler?index=1&url=#{lease_booking_path(booking)}" %></td>
      <% else %>
        <td><%= booking.id.to_s %></td>
      <% end %>
      <td><%= booking.lease_date %></td>      
      <td><%= booking.lease_item.name %></td>
      <td><%= booking.start_time %></td>
      <td><%= booking.total_hour %></td>
      <td><%= booking.customer.short_name %></td>  
      <td><%= booking.sales.name %></td>  
      <td><%= booking.completed %></td> 
      <td><%= booking.cancelled %></td>
      <% if has_edit_right?(booking) %>
        <td><%= link_to "Edit", SUBURI + "/view_handler?index=1&url=#{edit_lease_booking_path(booking)}" %></td>
      <% else %>
        <td></td>
      <% end %>
    </tr>
  <% end %>
</table>
<p>
<%= link_to 'Close', SUBURI + "/view_handler?index=0" %>|
<% if has_create_right? %>
  <%= link_to "输入Booking", SUBURI + "/view_handler?index=1&url=#{new_lease_booking_path}" %>|
<% end %>
<%= link_to to_chn(:search), search_lease_bookings_path %>
<%= link_to '统计', stats_lease_bookings_path if has_stats_right? %>
</p>
</div>

app/views/leasingx/lease_bookings/search_results.html.erb
<div id="main_body">
<h1><%=to_chn(:search_results)%> - 场地设备租赁</h1>
<p><%=@search_params %></p>
<p>总次数： <%=@lease_bookings.count %>, 
	小时数： <%= @lease_bookings.sum('total_hour') %>, 
	客户数量： <%= @lease_bookings.select("DISTINCT(customer_id)").count %>, 
	测试设备种类：<%= @lease_bookings.select("DISTINCT(lease_item_id)").count %>,
	完成次数： <%= @lease_bookings.where('completed = ?', true).count %>, 
	完成小时数： <%= @lease_bookings.where('completed = ?', true).sum('total_hour') %>, 	
	取消次数： <%= @lease_bookings.where('cancelled = ?', true).count %>, 
	取消小时数： <%= @lease_bookings.where('cancelled = ?', true).sum('total_hour') %>
</p>
<table>
  <tr>
  	<th>#</th>
    <th>租赁日期</th>
    <th>设备名称</th>    
    <th>开始时间</th>
    <th>小时数</th>
    <th>客户</th>
    <th>业务员</th>
    <th>完成？</th>
    <th>取消？</th>    
    <th></th>
    <th></th>
  </tr>
  <% @lease_bookings.each do |booking| %>
    <tr>
      <% if has_show_right?(booking) %>
        <td><%= link_to booking.id.to_s, SUBURI + "/view_handler?index=1&url=#{lease_booking_path(booking)}" %></td>
      <% else %>
        <td><%= booking.id.to_s %></td>
      <% end %>
      <td><%= booking.lease_date %></td>      
      <td><%= booking.lease_item.name %></td>
      <td><%= booking.start_time %></td>
      <td><%= booking.total_hour %></td>
      <td><%= booking.customer.short_name %></td>  
      <td><%= booking.sales.name %></td>  
      <td><%= booking.completed %></td> 
      <td><%= booking.cancelled %></td>
      <% if has_update_right? %>
        <td><%= link_to "Edit", SUBURI + "/view_handler?index=1&url=#{edit_lease_booking_path(booking)}" %></td>
      <% else %>
        <td></td>
      <% end %>
    </tr>
  <% end %>
</table>
<p>
<%= link_to 'Close', SUBURI + "/view_handler?index=0" %> | 
<% if has_create_right? %>
  <%= link_to "输入Booking", SUBURI + "/view_handler?index=1&url=#{new_lease_booking_path}" %> | 
<% end %>
<%= link_to to_chn(:search), search_lease_bookings_path %>
</p>
</div>

app/views/leasingx/lease_bookings/show.html.erb
<div id="main_body">
<h1>租赁Booking</h1>
 
<p class="notice"><%= notice %></p>
 
<p>
  <b>设备名称:</b>
  <%= @lease_booking.lease_item.name %>
</p>
 
<p>
  <b>客户:</b>
  <%= @lease_booking.customer.name %>
</p>
<p>
  <b>客户联系人:</b>
  <%= @lease_booking.leasee_name %>
</p> 
<p>
  <b>联系电话:</b>
  <%= @lease_booking.leasee_phone %>
</p>
<p>
  <b>开始时间:</b>
  <%= @lease_booking.start_time %>
</p>
<p>
  <b>结束时间</b>
  <%= @lease_booking.end_time %>
</p>
<p>
  <b>标准价格￥/小时</b>
  <%= @lease_booking.item_hourly_rate %>
</p>
<p>
  <b>小时数:</b>
  <%= @lease_booking.total_hour %>
</p>
<p>
  <b>实际价格/￥小时:</b>
  <%= @lease_booking.charge_rate %>
</p>
<p>
  <b>折扣%:</b>
  <%= @lease_booking.discount %>
</p>
<p>
  <b>租赁目的:</b>
  <%= @lease_booking.lease_purpose %>
</p>
<p>
  <b>完成？:</b>
  <%= @lease_booking.completed %>
</p>
<p>
  <b>取消？:</b>
  <%= @lease_booking.cancelled %>
</p>
<p>
  <b>注释:</b>
  <%= @lease_booking.note %>
</p>
<p>
  <b>业务员:</b>
  <%= @lease_booking.sales.name %>
</p>
<% if !@lease_booking.input_by_id.nil? && @lease_booking.input_by_id > 0 %>
<p>
  <b>输入/更改:</b>
  <%= @lease_booking.input_by.name %>
</p>
<% end %>
<p>
  <b>租赁Log:</b>
  <ul>
  <% @lease_booking.lease_logs.order("created_at DESC").each do |log| %>
  <li>
  	<%= link_to @log.input_by.name + ", 关于： "+log.subject + ", " + log.created_at.strftime('%Y-%m-%d').to_s, SUBURI + "/view_handler?index=1&url=#{lease_booking_lease_log_path(log.lease_booking_id, log.id)}" %>
  </li>
  <% end %>
  </ul>
</p>
 
<%= link_to 'Close', SUBURI + "/view_handler?index=0", :id => 'close' %>
<%= link_to @lease_booking.customer.short_name, SUBURI + "/view_handler?index=1&url=#{customer_path(@lease_booking.customer_id)}", :id => 'show_customer_link' %>
<%= link_to " 输入Log", new_lease_booking_lease_log_path(@lease_booking, :format => :js), :remote => true, :id => 'new_log_link' %>
</div>

app/views/leasingx/lease_bookings/stats_results.html.erb
<div id="main_body">
	<h1>设备出租Booking统计</h1>
<p><%= @stats_params %></p>
<table>
  <tr>
    <th>时段</th>       
    <th>金额（￥）</th>
    <th>(有效)小时数</th>
    <th>(平均)￥/小时</th>
    <th>客户数</th>
  </tr>
  <% @lease_bookings_stats.each do |booking| %>
    <tr>
      <td><%= booking.lease_date %></td>           
      <td><%= booking.revenue %></td>
      <td><%= booking.total_hours %></td>
      <td><%= (booking.revenue.to_f/booking.total_hours.to_f).round(2) if booking.total_hours.to_f > 0 %></td>
      <td><%= booking.num_customer %></td>
    </tr>
  <% end %>
</table>
<p>
<%= link_to 'Close',  stats_lease_bookings_path %>
</p>
</div>